import os
import glob
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))
import numpy as np
import vtk
import utils
import label_io
import marching_cube as m_c
def ground_truth_correction(gt_fn, im_fn, ids):
    """
    Map the registered ground truth images to surfaces generated by marching cube

    Args:
        gt_fn: vtk polydata filename
        im_fn: vtk image filename
        ids: ids of domains to remove
    Return:
        poly: mapped poly
    """
    # read and process image
    gt = label_io.loadVTKMesh(gt_fn) 
    im = label_io.loadLabelMap(im_fn)
    from vtk.util.numpy_support import vtk_to_numpy, numpy_to_vtk
    py_im = vtk_to_numpy(im.GetPointData().GetScalars())
    py_im = utils.swapLabels(py_im)

    for t_id in ids:
        py_im = utils.removeClass(py_im, t_id, 0)
    im.GetPointData().SetScalars(numpy_to_vtk(py_im))

    target = m_c.vtk_marching_cube_multi(im, 0, smooth=20, band=0.02)
    #debug
    locator = utils.pointLocator(target.GetPoints())

    #delete cap 
    face_ids = gt.GetCellData().GetAbstractArray('ModelFaceID')
    print(face_ids)
    gt.BuildLinks()
    for i in range(gt.GetNumberOfCells()):
        if face_ids.GetTuple(i)[0] != 1:
            gt.DeleteCell(i)
    gt.RemoveDeletedCells()
    gt.DeleteLinks()
    for i in range(gt.GetNumberOfPoints()):
        pt = gt.GetPoints().GetPoint(i)
        ids = locator.findNClosestPoints(pt, 3)
        avg_pt = (np.array(target.GetPoints().GetPoint(ids.GetId(0)))
        + np.array(target.GetPoints().GetPoint(ids.GetId(1)))
        + np.array(target.GetPoints().GetPoint(ids.GetId(2))))/3.
        gt.GetPoints().SetPoint(i, avg_pt)
    gt = utils.fillHole(gt)
    return gt 
if __name__=='__main__':

    poly_dir = '/Users/fanweikong/Documents/Modeling/SurfaceModeling/Label_based_results_gt/MACS40244_20150309/surfaces'
    im_dir ='/Users/fanweikong/Documents/ImageData/4DCCTA/MACS40244_20150309/wall_motion_labels_gt' 
    poly_dir_out = os.path.join(os.path.dirname(poly_dir), "surfaces_corrected")

    try:
        os.makedirs(poly_dir_out)
    except Exception as e: print(e)

    poly_fns = sorted(glob.glob(os.path.join(poly_dir, '*.vtk')))
    im_fns = sorted(glob.glob(os.path.join(im_dir, '*.nii.gz')))
    for poly_fn, im_fn in zip(poly_fns, im_fns):
        gt = ground_truth_correction(poly_fn, im_fn, [1, 4, 5, 7]) 
        label_io.writeVTKPolyData(gt, os.path.join(poly_dir_out, os.path.basename(poly_fn)))
